### ISSUE TITLE
renderers_and_plotly_chart  ValueError: Invalid format string

### ISSUE THREAD

**Issue by TekpreXyz** [tensortrade-org/tensortrade#272] opened 2020-12-28 13:29 UTC
Windows 10,
TensorTrade version:"1.0.1-beta"
TensorFlow version: 2.4
Python version: 3.8

![image](https://user-images.githubusercontent.com/73416709/103217430-da925d00-4918-11eb-8175-d0ee2fda754b.png)

ValueError: Invalid format string

**Comment by carlogrisetti** [comment] 2020-12-29 09:26
Issue is that for now windows date formats are not fully supported.
A valid workaround is to manually specify the correct date format within environment creation.

The parameter you're looking for is `renderer` and you can specify `default.renderers.ScreenLogger(date_format='%Y-%m-%d %H:%M:%S')` as a value. The same thing for other renderers, for example plotly would be `default.renderers.PlotlyTradingChart(display=False, timestamp_format='%Y-%m-%d %H:%M:%S', save_format='html', path='charts')`

**Comment by TekpreXyz** [comment] 2020-12-29 10:48
mmm ok, so do toy think that this can be related to this issue:
https://github.com/tensortrade-org/tensortrade/issues/275

**Comment by TekpreXyz** [comment] 2020-12-29 19:58
> Issue is that for now windows date formats are not fully supported.
> A valid workaround is to manually specify the correct date format within environment creation.
> 
> The parameter you're looking for is `renderer` and you can specify `default.renderers.ScreenLogger(date_format='%Y-%m-%d %H:%M:%S')` as a value. The same thing for other renderers, for example plotly would be `default.renderers.PlotlyTradingChart(display=False, timestamp_format='%Y-%m-%d %H:%M:%S', save_format='html', path='charts')`

i try that but don't worked

**Comment by TekpreXyz** [comment] 2020-12-30 06:11
ok after some try, as you suggest, the
`default.renderers.ScreenLogger(date_format='%Y-%m-%d %H:%M:%S')`
work, but when i change it to `default.renderers.PlotlyTradingChart(display=False, timestamp_format='%Y-%m-%d %H:%M:%S', save_format='html', path='charts')` i have this :

![image](https://user-images.githubusercontent.com/73416709/103333381-12f77f80-4a6e-11eb-8e87-02fd70fef20d.png)

i get 
ValueError: renderers() is missing required positional argument 'price_history'.

but how it can possible that whit default.renderers.ScreenLogger(date_format='%Y-%m-%d %H:%M:%S') it work?

**Comment by MichaelQuaMan** [comment] 2022-01-16 02:53
It looks like `DQNAgent` calls `render()` on its `env`, the `env` is supposed to fill in the `price_history` argument passed to: `render_env()` on `PlotlyTradingChart`

In `renderer.py` line 116
```
    def render(self, env: 'TradingEnv', **kwargs):

        price_history = None
        if len(env.observer.renderer_history) > 0:
            price_history = pd.DataFrame(env.observer.renderer_history)

        performance = pd.DataFrame.from_dict(env.action_scheme.portfolio.performance, orient='index')

        self.render_env(
            ...
            price_history=price_history,
            ...
        )
```
I'll try to figure out if `len(env.observer.renderer_history) > 0` is True.

**Comment by carlogrisetti** [comment] 2022-02-10 08:28
Although builtin agents are deprecated starting with 1.0.4, can you try if the recent modifications did have any impact to this?

**Comment by carlogrisetti** [comment] 2022-02-10 17:23
I mean not using Ray or stable_baselines or any other RL framework, but using the built-in agents provided by tensortrade.

Basically anything you import from tensortrade.agents (if I remember correctly, I'm on mobile rn)

**Comment by orthosku** [comment] 2022-02-17 06:06
Hi @MichaelQuaMan  - thanks for the detailed answer. I have a question with the "price_history" df.

looking at the docs it seems we're supposed to give it a pd df with o/h/l/c/volume and date; however when I put in my training df (which has all these components) it still throws the same error.

What then should I give the render_feed if not the training set?

**Comment by MichaelQuaMan** [comment] 2022-02-17 07:59
`price_history` is derived from Pandas Dataframe, i.e., it's a Panda Series/Column called with the "Close" prices.

It's then converted to a `list` here:
```
price_history[c].tolist()
```
in

```
renderer_feed = DataFeed([
    Stream.source(price_history[c].tolist(), dtype="float").rename(c) for c in price_history],
)
```

For example I am doing this:
```
file_name = "GBPUSD_M30.csv"
data_file = data_path + file_name
price_history = pd.read_csv('data/' + data_file)
columns = ["date", "open", "high", "low", "close", "volume"]
price_history .columns = columns
price_history.sort_values(by='date', ascending=True, inplace=True)
price_history.reset_index(drop=True, inplace=True)
```
and `price_history` become the Pandas Series of the `close` prices column from your data file here:
```
renderer_feed = DataFeed([
    Stream.source(price_history[c].tolist(), dtype="float").rename(c) for c in price_history],
)
```
The add `renderer_feed=renderer_feed` argument as shown in my previous post.

**If you are still getting:**
```
ValueError: renderers() is missing required positional argument 'price_history'.
```
Then `price_history` is `None`

As it states here:

![image](https://user-images.githubusercontent.com/4431953/154427819-19bb3c68-2a74-4c06-9694-f48d065c3667.png)

If you are sure you `price_history` variable is not `None`, then at some point between when giving to `DataFeed` and when it's checked in the conditional, in `renderers.py`, `price_history` is getting set to `None`. 

If I were you, I'd use a debugger and step through the code and follow the `price_history` variable. 

`PyCharm` and many other IDEs have decent GUI debuggers, 

or just use the command line debugger `pdb` (https://www.digitalocean.com/community/tutorials/how-to-use-the-python-debugger)

**Comment by carlogrisetti** [comment] 2022-02-27 11:45
Closing due to it being referred to an obsolete version.
Please reopen this issue if it can be reproduced with the most recent version, by installing it with
`pip install git+https://github.com/tensortrade-org/tensortrade.git`

Thanks!

**Closed by carlogrisetti** 2022-02-27 11:45 UTC

**Comment by orthosku** [comment] 2022-02-27 18:51
That was very helpful, thank you!

**Comment by carlogrisetti** [comment] 2022-02-27 19:04
> That was very helpful, thank you!

Have you managed to solve your issue?
